ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('app.urls',namespace="app")),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path,include

from .views import ItemList,ProductPage,CheckoutPage,add_to_cart,remove_from_cart,OrderSummary,remove_from_order,add_to_order,delete_now,handlerequest,CoupenCode


app_name="app"
urlpatterns=[
    path('',ItemList.as_view(),name='item_list'),
    path('products/<int:yo>',ProductPage.as_view(),name='product'),
    path('checkout/',CheckoutPage.as_view(),name='checkout'),
    path('order-summary/', OrderSummary.as_view(), name='order'),

    path('add/<int:yo>', add_to_cart.as_view(), name='add'),
    path('remove/<int:rem>', remove_from_cart.as_view(), name='remove'),
    path('remove-from-order/<int:rem>', remove_from_order.as_view(), name='remove1'),
    path('added-to-order/<int:rem>', add_to_order.as_view(), name='add1'),
    path('added-to-order/<int:rem>', add_to_order.as_view(), name='add1'),
    path('delete/<int:rem>', delete_now.as_view(), name='delete'),
    path('handlerequest/', handlerequest.as_view(), name='handlerequest'),
    path('coupon/',CoupenCode.as_view(),name="coupon")

]

models.py
from django.db import models
from django.conf import settings
from django_countries.fields import CountryField
CATEGORY_CHOICES=(
    ('S','Shirt'),
    ('SW', 'Sport Wear'),
    ('OW', 'OutWear')
)
LABEL_CHOICES=(
    ('P','primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)
ADDRESS_CHOICES=(
    ('B','Billing'),
    ('S','Shipping'),
)
class Item(models.Model):
    title=models.CharField(max_length=100)
    price=models.FloatField()
    discountprice = models.FloatField(blank=True,null=True)
    category=models.CharField(choices=CATEGORY_CHOICES,max_length=2)
    label=models.CharField(choices=LABEL_CHOICES,max_length=1)
    description=models.TextField()
    quantity=models.IntegerField(default=1)
    image=models.ImageField()
    def __str__(self):
        return self.title

class OrderItem(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ordered=models.BooleanField(default=False)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    def get_total_item_price(self):
        return self.quantity*self.item.price
    def get_discount_price(self):
        return self.quantity*self.item.discountprice
    def get_save(self):
        return self.get_total_item_price()-self.get_discount_price()
    def get_final_price(self):
        if self.item.discountprice:
            return self.get_discount_price()
        else:
            return self.get_total_item_price()
#Like a Shopping cart
class Order(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    items=models.ManyToManyField(OrderItem)
    start_date=models.DateTimeField(auto_now_add=True)
    ordered_date=models.DateTimeField()
    ordered=models.BooleanField(default=False)
    billing=models.ForeignKey('BillingAddress',on_delete=models.SET_NULL,blank=True,null=True,related_name='biiling_address')
    shipping=models.ForeignKey('BillingAddress',on_delete=models.SET_NULL,blank=True,null=True,related_name='shipping_adress')
    coupon=models.ForeignKey('Coupon',on_delete=models.SET_NULL,blank=True,null=True)
    def __str__(self):
        return self.user.username

    def total(self):
        total=0
        for order_item in self.items.all():
            total=total+order_item.get_final_price()
        if self.coupon:
            total-=self.coupon.amount
        return total

class BillingAddress(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    Address=models.CharField(max_length=100)
    apartment_add=models.CharField(max_length=100)
    country=CountryField(multiple=False)
    zip=models.CharField(max_length=100)
    address_type=models.CharField(max_length=1,choices=ADDRESS_CHOICES,null=True,blank=True)
    default=models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code=models.CharField(max_length=20)
    amount=models.FloatField()
    def __str__(self):
        return self.code

templates/app/checkout-page.html
{%extends "app/base.html"%}
{%block content%}
{%load crispy_forms_tags%}
{%load cart_template_tags%}
  <!--Main layout-->
  <main class="pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">
            <form method="post" class="ml-2 mr-2 my-2">
              {%csrf_token%}
              {{form|crispy}}
              <button class="btn btn-primary btn-lg text-center" type="submit" style="width:100%">CheckOut</button>
            </form>
            <!--Card content-->

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{request.user|cart_item_count}}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            {%for order_list in order.items.all%}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{order_list.item.title}}</h6>
              </div>
              <span class="text-muted">{{order_list.get_final_price}}</span>
            </li>
            {%endfor%}
            {%if order.coupon%}
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{order.coupon}}</small>
              </div>
              <span class="text-success">{{order.coupon.amount}}</span>
            </li>
            {%endif%}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total(Rs.)</span>
              <strong>{{order.total}}</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2" method="post" action="{%url 'app:coupon'%}">
            <div class="input-group">
              {%csrf_token%}
              {{coupon.code}}
              <div class="input-group-append text-center">
                <button class="btn btn-secondary btn-md waves-effect ml-5" type="submit">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  {%endblock%}

templates/app/home-page.html
{%extends "app/base.html"%}
{%block content%}

  <!--Main layout-->
  <main >
    <div class="container" style="margin-top:20px;">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->

          {%for item in object_list%}
            <div class="col-lg-3 col-md-6 mb-4">
              <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{item.image.url}}" class="card-img-top"
                  alt="">
                <a href="{%url 'app:product' item.id%}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{item.get_category_display}}</h5>
                </a>
                <h6>
                  <strong>
                    <a href="{%url 'app:product' item.id%}" class="dark-grey-text">{{item.title}}
                    <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                    </a>
                  </strong>
                </h6>

                <h4 class="font-weight-bold blue-text">

                  <strong>
                    {%if item.discountprice%}
                    <del>{{item.price}}</del>
                    <span>{{item.discountprice}}</span>
                    {%else%}
                    {{item.price}}
                    {%endif%}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->
            </div>
            {%endfor%}

          </div>
          <!--Fourth column-->

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
    {%if is_paginated%}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {%if page_obj.has_previous%}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {%endif%}
          <li class="page-item active">
            <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {%if page_obj.has_next%}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {%endif%}
        </ul>
      </nav>
    {%endif%}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->

{%endblock%}

templates/app/items.html
{%extends 'app/base.html'%}
{%block content%}
    <h1>Here is the list of items</h1>
    {%for item in items%}
        <!--<h1>{{item.title}}</h1>
        <h2>{{item.price}}</h2>-->
        <h1>{{item}}</h1>
    {%endfor%}
{%endblock%}

templates/app/order.html
{%extends "app/base.html"%}
{%block content%}

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->

            <div class="table-responsive text-nowrap">
        {%if message%}
            <h2 style="margin-top:20px;">{{message}}</h2>
        {%else%}
        <h2 style="margin-top:20px;font-weight:bold">Order Summary</h2>
  <table class="table my-3">
    <thead>
      <tr>
          <th>#</th>
        <th scope="col">Item Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Item Price</th>

      </tr>
    </thead>
    <tbody>
    {%for order_item in order.items.all%}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{order_item.item.title}}</td>
        <td>{{order_item.item.price}}</td>
        <td><a href="{%url "app:remove1" order_item.item.id%}"><i class="fas fa-minus"></i></a>&nbsp{{order_item.quantity}}&nbsp<a href="{%url "app:add1" order_item.item.id%}"><i class="fas fa-plus-square"></i></a></td>
        <td>
            {%if order_item.item.discountprice%}
            {{order_item.get_discount_price}}
            <span class="badge badge-primary">(Saving Rs.{{order_item.get_save|floatformat:2}})</span>
            {%else%}
            {{order_item.get_total_item_price}}
            {%endif%}
        </td>
          <td><a href="{%url "app:delete" order_item.item.id%}"><i class="fas fa-trash"></i></a></td>
      </tr>

    {%endfor%}
        <tr>
            <td style="font-size:15px"><b>Order Total</b></td>
            <td></td>
            <td></td>
            <td></td>
        <td style="font-size:15px"><b>Rs.{{order.total}}</b></td>
    </tr>
    <hr/>
    <tr>
        <td colspan="7">
            <a class="btn btn-warning float-center mr-2" href="{%url 'app:item_list'%}" >Continue Shopping</a>

            <a class="btn btn-primary float-center" href="{%url 'app:checkout'%}" >Proceed to Checkout</a>
        </td>
    </tr>
    </tbody>
  </table>
{%endif%}
</div>



        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->


    </div>
  </main>
  <!--Main layout-->

{%endblock%}

templates/app/paymentstatus.html
{%extends "app/base.html"%}

{%load crispy_forms_tags%}
{%block content%}
  <!--Main layout-->
  <main class="pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Payment Status</h2>
        <h2 style="text-align:center;margin-top:30px;>Payment status regarding your order Id {{response.ORDERID}}</h2>
        {% if response.RESPCODE == '01' %}
        <h2 style="text-align:center;margin-top:30px;>Order Placed successfully!</h2>
        {% else %}
        <h2 style="text-align:center;my-2;">Order Failure!</h2>
        {% endif%}
        <h3 style="text-align:center;margin-top:60px;"><a href="{%url 'app:item_list'%}">Click here to go back to home page.</a></h3>



    </div>
  </main>
  <!--Main layout-->

{%endblock%}

templates/app/paytm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paytm Merchant payment page</title>
</head>
<body>
<h1>Redirecting you to the Merchant...</h1>
<h1>Please do not refresh the page...</h1>
<form action="https://securegw.paytm.in/theia/processTransaction" method="post" name="paytm">
    {%for item,item1 in param_dict.items%}
    <input type="hidden" name="{{item}}" value="{{item1}}">
    {%endfor%}

</form>
</body>
<script>
document.paytm.submit()
</script>
</html>

templates/app/product-page.html
{%extends "app/base.html"%}
{%block content%}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{item.image.url}}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{item.get_category_display}}</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              <span class="mr-2">
                    {%if item.discountprice%}
                    <del>{{item.price}}</del>
                    <span>{{item.discountprice}}</span>
                    {%else%}
                    {{item.price}}
                    {%endif%}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{item.description}}</p>

            <!--<form class="d-flex justify-content-left">

              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form>-->
                          <a href="{%url 'app:add' item.id%}" class="btn btn-primary btn-lg my-0 p">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
                    <a href="{%url 'app:remove' item.id%}" class="btn btn-danger btn-lg my-3 p">Remove from cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>



          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{%endblock%}